version: '3.7'

services:
  site:
    container_name: site-container
    build: ./
    command: python app.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=nolla
      - MYSQL_PASSWORD=nolla
      - MYSQL_DATABASE=nolla
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin-container
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=nolla
      - PMA_PASSWORD=nolla
    ports:
      - 8080:80

volumes:
  mysql-data:
    name: test-mysql-data
