version: '3.7'

services:
  site:
    build: ./site
    command: python app.py
    volumes:
      - ./site/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=nolla
      - MYSQL_PASSWORD=nolla
      - MYSQL_DATABASE=nolla
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=nolla
      - PMA_PASSWORD=nolla
    ports:
      - 5050:80

volumes:
  mysql_data:
