"""empty message

Revision ID: 82e8c9d61340
Revises: 
Create Date: 2020-02-29 03:04:29.544509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82e8c9d61340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_categories')
    op.drop_table('media_type')
    op.drop_table('pwdrecover')
    op.drop_index('username_2', table_name='user')
    op.drop_table('user')
    op.drop_index('kartta_id_2', table_name='map_spot')
    op.drop_table('map_spot')
    op.drop_index('media_id_2', table_name='media')
    op.drop_table('media')
    op.drop_index('id_2', table_name='comment')
    op.drop_index('staattinen_id', table_name='comment')
    op.drop_table('comment')
    op.drop_table('uploads')
    op.drop_table('countries')
    op.drop_table('map_country')
    op.drop_index('paikkakunta', table_name='map_town')
    op.drop_table('map_town')
    op.drop_table('genre')
    op.drop_table('map_type')
    op.drop_table('links')
    op.drop_table('story_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('links',
    sa.Column('id', mysql.INTEGER(display_width=6, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('category', mysql.INTEGER(display_width=50), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=50), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('map_type',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('genre',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('map_town',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('paikkakunta', mysql.VARCHAR(length=40), server_default=sa.text("''"), nullable=False),
    sa.Column('maa_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('lat', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('lon', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('paikkakunta', 'map_town', ['paikkakunta'], unique=True)
    op.create_table('map_country',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('maa', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('lat', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('lon', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('koodi', mysql.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('countries',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('country_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('country_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('uploads',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('path', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('comment',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('header', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('comment', mysql.LONGTEXT(), nullable=True),
    sa.Column('media_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('comment_user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('youtube_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tapahtuma_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('diary_id', mysql.INTEGER(display_width=20), autoincrement=False, nullable=True),
    sa.Column('kilpailu_id', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('videoblog_id', mysql.INTEGER(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('staattinen_id', 'comment', ['kilpailu_id'], unique=False)
    op.create_index('id_2', 'comment', ['id'], unique=True)
    op.create_table('media',
    sa.Column('media_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('media_type', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('media_genre', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('story_type', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('media_topic', mysql.TINYTEXT(), nullable=False),
    sa.Column('media_desc', mysql.TEXT(), nullable=True),
    sa.Column('media_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('owner', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('other', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('type', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('lyhyt', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('media_file', mysql.LONGBLOB(), nullable=True),
    sa.Column('media_file_size', mysql.TINYTEXT(), nullable=True),
    sa.Column('media_file_type', mysql.TINYTEXT(), nullable=True),
    sa.Column('lyhyt_ok', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('lang_id', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hidden', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='Media is hidden when value is 1'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_pack_keys='1'
    )
    op.create_index('media_id_2', 'media', ['media_id'], unique=True)
    op.create_table('map_spot',
    sa.Column('kartta_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('paikkakunta_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('nimi', mysql.VARCHAR(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('info', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('tyyppi', mysql.SMALLINT(display_width=5, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('temp', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('paivays', sa.DATE(), server_default=sa.text("'0000-00-00'"), nullable=False),
    sa.Column('karttalinkki', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('maa_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('latlon', mysql.TINYTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('kartta_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('kartta_id_2', 'map_spot', ['kartta_id'], unique=True)
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('level', mysql.TINYINT(display_width=4), server_default=sa.text("'99'"), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('name', mysql.TINYTEXT(), nullable=False),
    sa.Column('bornyear', mysql.SMALLINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('email', mysql.TINYTEXT(), nullable=False),
    sa.Column('email2', mysql.TINYTEXT(), nullable=True),
    sa.Column('homepage', mysql.TINYTEXT(), nullable=True),
    sa.Column('info', mysql.LONGTEXT(), nullable=True),
    sa.Column('location', mysql.TINYTEXT(), nullable=False),
    sa.Column('date', sa.DATE(), server_default=sa.text("'0000-00-00'"), nullable=False),
    sa.Column('hobbies', mysql.TEXT(), nullable=True),
    sa.Column('open', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('extrainfo', mysql.TINYTEXT(), nullable=True),
    sa.Column('sukupuoli', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('icq', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('apulainen', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('chat', mysql.INTEGER(display_width=4, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('oikeus', mysql.TINYINT(display_width=2), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('lang_id', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('login_count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('lastloginip', mysql.TINYTEXT(), nullable=True),
    sa.Column('lastloginclient', mysql.TINYTEXT(), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('postnumber', mysql.TINYTEXT(), nullable=False),
    sa.Column('emails', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('puhelin', mysql.TINYTEXT(), nullable=True),
    sa.Column('kantaasiakasnro', mysql.TINYTEXT(), nullable=True),
    sa.Column('lamina_lisatieto', mysql.LONGTEXT(), nullable=True),
    sa.Column('blogs', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_showid', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('blog_level', mysql.TINYINT(display_width=4), server_default=sa.text("'5'"), autoincrement=False, nullable=False),
    sa.Column('last_login2', mysql.DATETIME(), nullable=True),
    sa.Column('messenger', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('myspace', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('rss', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('youtube', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ircgalleria', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_profile_update', mysql.TIMESTAMP(), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('flickr_username', mysql.TINYTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_pack_keys='1'
    )
    op.create_index('username_2', 'user', ['username'], unique=False)
    op.create_table('pwdrecover',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('media_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('link_categories',
    sa.Column('id', mysql.INTEGER(display_width=6, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=50), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
